#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor eDP1 -d  I II III IV V

########## Window Settings ##############
bspc config border_width        0
bspc config window_gap          7 
bspc config focus_follows_pointer   true
bspc config split_ratio         0.50 
bspc config borderless_monocle  true
bspc config gapless_monocle     true
########## Border Colors #################
# bspc config focused_border_color "#2E3440"
# bspc config normal_border_color  "#2E3440"

######### Program settings ################
######## Use xprop WM Class String ########
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a imv desktop='^2' follow=on
bspc rule -a mpv desktop='^2' follow=on
bspc rule -a Zathura desktop='^2' follow=on
bspc rule -a Gimp desktop='^3' follow=on
bspc rule -a Pcmanfm desktop='^4' follow=on
bspc rule -a St desktop='^3' follow=on
bspc rule -a thunderbird desktop='^5' follow=on

#Extra
xsetroot -xcf /usr/share/icons/Numix-Cursor/cursors/left_ptr 16
xrandr --output eDP1 --brightness 0.8 --mode 1368x768 --rate 60
xbacklight -set 20

# xrandr --output eDP1 --mode 1368x768 --rate 30
picom &
# redshift -l lat:long &

#Wallpaper
~/.fehbg

######### My Polybar ###############
polybar left &
polybar right &

## Undervolt & underclock
# sudo intel-undervolt apply
# sudo cpupower frequency-set --governor ondemand --min 500MHz --max 1.5GHz

# ram management
# earlyoom -r 0 --avoid '(^|/)(dinit|bspwm|polybar|picom)$' --prefer '(^|/)(figma-linux|java|google-chrome-stable)$' -m 10 &
